#!/bin/sh
set -e
lb config noauto --distribution noble --architectures amd64 --binary-images iso-hybrid --archive-areas "main universe multiverse restricted" --bootappend-live "boot=live components quiet splash" --debian-installer none --apt-recommends true
