#!/bin/sh
set -e
lb config noauto \
  --distribution noble \
  --mode ubuntu \
  --system normal \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --archive-areas "main restricted universe multiverse" \
  --mirror-bootstrap "https://archive.ubuntu.com/ubuntu/" \
  --mirror-chroot "https://archive.ubuntu.com/ubuntu/" \
  --mirror-binary "https://archive.ubuntu.com/ubuntu/" \
  --mirror-chroot-security "https://security.ubuntu.com/ubuntu/" \
  --mirror-binary-security "https://security.ubuntu.com/ubuntu/" \
  --keyring-packages ubuntu-keyring \
  --syslinux-theme "live-build" \
  --bootappend-live "boot=live components quiet splash" \
  --apt-recommends true
